image: Ubuntu

stack: jdk 11

branches:
  only:
    - main
    - JSON_Schema

build: off

install:
  - java -jar ./artifacts/app-mbank.jar &

build_script:
  - chmod +x gradlew
  - ./gradlew test --info